### ISSUE TITLE
bundle install reports warning when installing gem from github

### ISSUE THREAD

**Issue by dkharrat** [bdurand/acts_as_revisionable#3]
I noticed that rubygems.org still has the old version (1.0.6) of this gem. When do you plan to push the new version to rubygems?

In the meantime, in my Gemfile, I tried installing the gem from your repo in github directly as follows:

```
gem 'acts_as_revisionable', :git => "git://github.com/bdurand/acts_as_revisionable.git"
```

but I get the following error:

`acts_as_revisionable at /home/dk/.rvm/gems/ruby-1.9.2-p180/bundler/gems/acts_as_revisionable-812e2dad99db did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
  ["spec/full_spec.rb"] are not files`

**Comment by bdurand** [comment]
I just pushed version 1.1.0. Please note that if you are already using a 1.0 release of the gem you'll need to add a migration to update the revisions table to the new version.
